spec:
  type: NodePort
  selector:
    app: JenkinsTest
    tier: JenkinsTest
  ports:
  - name: http
    protocol: TCP
    nodePort: 8080
    port: 8080
    targetPort: 80
metadata:
  name: JenkinsTest
  labels:
    app: JenkinsTest
kind: Service
apiVersion: v1

---
spec:
  template:
    metadata:
      labels:
        app: JenkinsTest
        tier: JenkinsTest
    spec:
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 1.1.1.1
      containers:
      - image: '{{registry_host}}/JenkinsTest:{{tag}}'
        name: JenkinsTest
        ports:
        - name: http
          protocol: TCP
          containerPort: 5000
        resources:
          limits:
            memory: 2000Mi
            cpu: "4"
          requests:
            memory: 1000Mi
            cpu: "1"
  replicas: 3
  strategy:
    type: Recreate
metadata:
  name: JenkinsTest
  labels:
    app: JenkinsTest
kind: Deployment
apiVersion: apps/v1beta1